
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: spec-sandro-mr-teste-app-cors
plugin: cors
config:
  origins:
    - https://devportal-homolog.apr.vee.codes
    - https://devportal.apr.vee.codes
  credentials: false
  max_age: 3600
  preflight_continue: false
---
apiVersion: v1
kind: Service
metadata:
  name: spec-sandro-mr-teste-app
spec:
  externalName: viacep.com.br
  type: ExternalName
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    konghq.com/methods: GET
    konghq.com/regex-priority: "100"
    konghq.com/strip-path: "false"
    konghq.com/plugins: spec-sandro-mr-teste-app-cors
  name: spec-sandro-mr-teste-app-viacep-viacep-getaddressbyzip-code
spec:
  ingressClassName: kong
  rules:
    - http:
        paths:
          - backend:
              service:
                name: spec-sandro-mr-teste-app
                port:
                  number: 80
            path: /~/spec-sandro-mr-teste-app/ws/(?<zip_code>[^#?/]+)/json$
            pathType: ImplementationSpecific
      host: vkpr.platform.vee.codes
---

